
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 17 00:11:27 GMT-03:00 2010
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FORALL = 7;
  public static final int PONTOVIRGULA = 35;
  public static final int EXCLUDES = 13;
  public static final int POS = 3;
  public static final int MENORQ = 27;
  public static final int LCHAVE = 20;
  public static final int XOR = 44;
  public static final int MAIORQ = 28;
  public static final int INTEGER = 58;
  public static final int LPAREN = 16;
  public static final int INV = 4;
  public static final int RCHAVE = 21;
  public static final int MAIORIGUAL = 30;
  public static final int PRE = 2;
  public static final int VIRGULA = 24;
  public static final int PONTO = 33;
  public static final int RPAREN = 17;
  public static final int NOT = 45;
  public static final int AND = 42;
  public static final int MENORIGUAL = 29;
  public static final int INCLUDES = 12;
  public static final int IGUAL = 25;
  public static final int OR = 43;
  public static final int MAIS = 37;
  public static final int IMPLIES = 11;
  public static final int BAG = 55;
  public static final int COLLECTION = 57;
  public static final int SELECT = 5;
  public static final int IF = 8;
  public static final int ID = 62;
  public static final int CONTEXT = 15;
  public static final int BOOLEAN = 52;
  public static final int EOF = 0;
  public static final int TRUE = 60;
  public static final int SIZE = 14;
  public static final int error = 1;
  public static final int MENOS = 38;
  public static final int EXISTS = 6;
  public static final int NUMBER = 53;
  public static final int VOID = 41;
  public static final int PONTOPONTO = 32;
  public static final int REAL = 59;
  public static final int ENDPACKAGE = 50;
  public static final int REALTYPE = 48;
  public static final int BARRA = 36;
  public static final int ENDIF = 46;
  public static final int ELSE = 10;
  public static final int SHARP = 34;
  public static final int DIVIDIR = 40;
  public static final int PACKAGE = 49;
  public static final int INTTYPE = 47;
  public static final int THEN = 9;
  public static final int STRING = 51;
  public static final int DIFF = 26;
  public static final int SEQUENCE = 56;
  public static final int LCOLCH = 18;
  public static final int FALSE = 61;
  public static final int QUATROPONTOS = 23;
  public static final int VEZES = 39;
  public static final int SET = 54;
  public static final int SETA = 31;
  public static final int DOISPONTOS = 22;
  public static final int RCOLCH = 19;
}

