
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Sep 19 20:13:10 GMT-03:00 2010
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FORALL = 7;
  public static final int PONTOVIRGULA = 36;
  public static final int EXCLUDES = 13;
  public static final int POS = 3;
  public static final int MENORQ = 28;
  public static final int LCHAVE = 21;
  public static final int XOR = 54;
  public static final int MAIORQ = 29;
  public static final int INTEGER = 50;
  public static final int LPAREN = 17;
  public static final int INV = 4;
  public static final int RCHAVE = 22;
  public static final int MAIORIGUAL = 31;
  public static final int PRE = 2;
  public static final int VIRGULA = 25;
  public static final int PONTO = 34;
  public static final int RPAREN = 18;
  public static final int NOT = 55;
  public static final int AND = 52;
  public static final int MENORIGUAL = 30;
  public static final int INCLUDES = 12;
  public static final int IGUAL = 26;
  public static final int OR = 53;
  public static final int MAIS = 38;
  public static final int IMPLIES = 11;
  public static final int BAG = 47;
  public static final int COLLECTION = 49;
  public static final int SELECT = 5;
  public static final int IF = 8;
  public static final int ID = 42;
  public static final int CONTEXT = 16;
  public static final int BOOLEAN = 44;
  public static final int EOF = 0;
  public static final int TRUE = 62;
  public static final int SIZE = 15;
  public static final int error = 1;
  public static final int MENOS = 39;
  public static final int EXISTS = 6;
  public static final int NUMBER = 45;
  public static final int VOID = 51;
  public static final int PONTOPONTO = 33;
  public static final int REAL = 61;
  public static final int ENDPACKAGE = 60;
  public static final int REALTYPE = 58;
  public static final int BARRA = 37;
  public static final int ENDIF = 56;
  public static final int SHARP = 35;
  public static final int ELSE = 10;
  public static final int DIVIDIR = 41;
  public static final int PACKAGE = 59;
  public static final int INTTYPE = 57;
  public static final int THEN = 9;
  public static final int STRING = 43;
  public static final int DIFF = 27;
  public static final int SEQUENCE = 48;
  public static final int LCOLCH = 19;
  public static final int FALSE = 63;
  public static final int QUATROPONTOS = 24;
  public static final int VEZES = 40;
  public static final int SET = 46;
  public static final int RESULT = 14;
  public static final int SETA = 32;
  public static final int DOISPONTOS = 23;
  public static final int RCOLCH = 20;
}

